apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-information-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-local-app
  template:
    metadata:
      labels:
        app: my-local-app
    spec:
      containers:
        - name: my-local-container
          image: student-informaiton-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: student-information-service-service
spec:
  selector:
    app: my-local-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: NodePort